queueserver:
  image: mongo:3.2.6

skoleskyss:
  image: telemark/skoleskyss.t-fk.no
  #build: .
  container_name: skoleskyss
  env_file: skoleskyss.env
  restart: always
  links:
    - queueserver
  ports:
    - 8000:8000