queueserver:
  image: mongo:3.2.6

sessionserver:
  image: mongo:3.2.6

services_base:
  image: telemark/tfk-seneca-base
  container_name: services_base
  env_file: skoleskyss.env
  restart: always
  net: container:skoleskyss_web

services_session:
  image: telemark/tfk-seneca-session
  container_name: services_session
  env_file: skoleskyss.env
  restart: always
  net: container:skoleskyss_web

skoleskyss_web:
  image: telemark/skoleskyss.t-fk.no
  container_name: skoleskyss
  env_file: skoleskyss.env
  restart: always
  links:
    - queueserver
    - sessionserver
  ports:
    - 8000:8000